#! /bin/bash

sed -E 's/\?|<u>|<\/u>//g' |
tr '`-' "\' " |
tr 'A-Z' 'a-z' |
grep -Eo "[[:space:]]*<td[^>]*>[\'pkmnwlhaeiou[:space:]]*</td>[[:space:]]*" |
sed -E 's/[[:space:]]*<td[^>]*>|<\/td>[[:space:]]*//g' |
tr -s '[:space:]' '\n' |
sort -u
